// Code generated by qtc from "tenants_response.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vlselect/logsql/tenants_response.qtpl:3
package logsql

//line app/vlselect/logsql/tenants_response.qtpl:3
import (
	"github.com/VictoriaMetrics/VictoriaLogs/lib/logstorage"
)

// TenantsResponse generates response for /admin/tenants .

//line app/vlselect/logsql/tenants_response.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vlselect/logsql/tenants_response.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vlselect/logsql/tenants_response.qtpl:8
func StreamTenantsResponse(qw422016 *qt422016.Writer, tenants []logstorage.TenantID) {
//line app/vlselect/logsql/tenants_response.qtpl:8
	qw422016.N().S(`{"status":"success","data":[`)
//line app/vlselect/logsql/tenants_response.qtpl:12
	for i, tenant := range tenants {
//line app/vlselect/logsql/tenants_response.qtpl:12
		qw422016.N().S(`"`)
//line app/vlselect/logsql/tenants_response.qtpl:13
		qw422016.N().D(int(tenant.AccountID))
//line app/vlselect/logsql/tenants_response.qtpl:13
		qw422016.N().S(`:`)
//line app/vlselect/logsql/tenants_response.qtpl:13
		qw422016.N().D(int(tenant.ProjectID))
//line app/vlselect/logsql/tenants_response.qtpl:13
		qw422016.N().S(`"`)
//line app/vlselect/logsql/tenants_response.qtpl:14
		if i+1 < len(tenants) {
//line app/vlselect/logsql/tenants_response.qtpl:14
			qw422016.N().S(`,`)
//line app/vlselect/logsql/tenants_response.qtpl:14
		}
//line app/vlselect/logsql/tenants_response.qtpl:15
	}
//line app/vlselect/logsql/tenants_response.qtpl:15
	qw422016.N().S(`]}`)
//line app/vlselect/logsql/tenants_response.qtpl:18
}

//line app/vlselect/logsql/tenants_response.qtpl:18
func WriteTenantsResponse(qq422016 qtio422016.Writer, tenants []logstorage.TenantID) {
//line app/vlselect/logsql/tenants_response.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vlselect/logsql/tenants_response.qtpl:18
	StreamTenantsResponse(qw422016, tenants)
//line app/vlselect/logsql/tenants_response.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line app/vlselect/logsql/tenants_response.qtpl:18
}

//line app/vlselect/logsql/tenants_response.qtpl:18
func TenantsResponse(tenants []logstorage.TenantID) string {
//line app/vlselect/logsql/tenants_response.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vlselect/logsql/tenants_response.qtpl:18
	WriteTenantsResponse(qb422016, tenants)
//line app/vlselect/logsql/tenants_response.qtpl:18
	qs422016 := string(qb422016.B)
//line app/vlselect/logsql/tenants_response.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vlselect/logsql/tenants_response.qtpl:18
	return qs422016
//line app/vlselect/logsql/tenants_response.qtpl:18
}
