name: build

on:
  push:
    branches:
      - master
    paths:
      - '**.go'
      - '**/Dockerfile'
      - '**/Makefile'
      - '!app/vmui/Makefile'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**.go'
      - '**/Dockerfile'
      - '**/Makefile'
      - '!app/vmui/Makefile'
      - '.github/workflows/build.yml'

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Setup Go
        id: go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: false

      - name: Cache Go artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/bin
            ~/go/pkg/mod
          key: go-artifacts-${{ runner.os }}-crossbuild-${{ steps.go.outputs.go-version }}-${{ hashFiles('go.sum', 'Makefile', 'app/**/Makefile') }}
          restore-keys: go-artifacts-${{ runner.os }}-crossbuild-

      - name: Run crossbuild
        run: make crossbuild
